out_of_stock_rules:
  path: out-of-stock/rules
  methods: [GET]
  defaults:
    _controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::indexAction
#    _legacy_controller: AdminLinkWidget
#    _legacy_link: 'MyModuleDemoController'

out_of_stock_rules_search:
  path: out-of-stock/rules
  methods: [POST]
  defaults:
    _controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::searchAction
    _legacy_controller: 'Admin\OutOfStockReminderController'
    _legacy_link: 'Admin\OutOfStockReminderController:search'

sent_rule:
  path: out-of-stock/store-rules
  methods: [POST]
  defaults:
    _controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::storeAction

admin_link_block_list:
  path: /link-widget/list
  methods: [GET]
  defaults:
    _controller: PrestaShop\Module\LinkList\Controller\Admin\Improve\Design\LinkBlockController::listAction
    # _legacy_controller is used to manage permissions
    _legacy_controller: AdminLinkWidget
    # No need for _legacy_link in this case

out_of_stock/create_rule:
  path: out-of-stock/create-rule
  controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::createAction

out_of_stock_edit:
  path: out-of-stock/edit/{id}
  methods: [GET]
  defaults:
    _controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::editAction

out_of_stock_update:
  path: out-of-stock/update/{id}
  methods: [POST]
  defaults:
    _controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::updateAction

out_of_stock_delete:
  path: out-of-stock/delete/{id}
  methods: [POST]
  defaults:
    _controller: OutOfStockReminder\Controller\Admin\OutOfStockReminderController::deleteAction

out_of_stock/send_emails:
  path: out-of-stock/send-emails
  methods: [GET]
  controller: OutOfStockReminder\Controller\Admin\EmailController::sendMails

out_of_stock/toggle_status:
  path: out-of-stock/toggle-status/{id}
  methods: [POST]
  controller: OutOfStockReminder\Controller\Admin\StatusController::toggleStatus