services:
  out_of_stock_reminder.grid.definition.factory.rules:
    class: 'OutOfStockReminder\Grid\Definition\Factory\RuleGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  out_of_stock_reminder.grid.query_builder.rule:
    class: 'OutOfStockReminder\Grid\Query\RuleQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'


  out_of_stock_reminder.grid.data_provider.rules:
    public: true
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@out_of_stock_reminder.grid.query_builder.rule'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'rules'

  out_of_stock_reminder.grid.factory.rules:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@out_of_stock_reminder.grid.definition.factory.rules'
      - '@out_of_stock_reminder.grid.data_provider.rules'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
      -


