services:
  out_of_stock_reminder.grid.definition.factory.rules:
    class: 'OutOfStockReminder\Grid\Definition\Factory\RuleGridDefinitionFactory'
    parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    public: true

  out_of_stock_reminder.grid.query_builder.rule:
    class: 'OutOfStockReminder\Grid\Query\RuleQueryBuilder'
    parent: 'prestashop.core.grid.abstract_query_builder'
    public: true
    arguments:
      - '@prestashop.core.query.doctrine_search_criteria_applicator'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
      - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
      - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
      - '@prestashop.adapter.legacy.configuration'


  out_of_stock_reminder.grid.data_provider.rules:
    public: true
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    arguments:
      - '@out_of_stock_reminder.grid.query_builder.rule'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'rule'
# Configure our Grid Data factory to use the query builder that we registered above
  out_of_stock_reminder.grid.factory.rules:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    public: true
    arguments:
      - '@out_of_stock_reminder.grid.definition.factory.rules'
      - '@out_of_stock_reminder.grid.data_provider.rules'
      - '@prestashop.core.grid.filter.form_factory'
#      - '@prestaShop.prestaShop.core.grid.filter.grid_filter_form_factory_interface'
      - '@prestashop.core.hook.dispatcher'
      -
#  prestashop.core.form.identifiable_object.data_provider.rule_form_data_provider:
#    class: 'OutOfStockReminder\Form\RuleFormDataProvider'
#
#  prestashop.module.outofstockreminder.form.rule_form_data_handler:
#    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
#    public: true
#    arguments:
#      - '@form.factory'
#      - '@prestashop.core.hook.dispatcher'
#      - '@prestashop.module.outofstockreminder.form.rule_form_data_provider'
#      - 'PrestaShop\Module\DemoSymfonyFormSimple\Form\DemoConfigurationFormType'
#      - 'OutOfStockReminder'


